require:
  - standard
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  # Enable all the rules by default
  EnabledByDefault: true
  # Command line rubocop options
  ExtraDetails: true
  DisplayStyleGuide: true
  DisplayCopNames: true
  SuggestExtensions: false
  # Target versions
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.1

#-------------------------------------------------------------------------------
# RSpec rules
#-------------------------------------------------------------------------------

RSpec/MultipleExpectations:
  Max: 7

# Name your test subject if you need to reference it explicitly. (http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/NamedSubject)
RSpec/NamedSubject:
  Enabled: false

# Spec path should end with _spec (http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FilePath)
# example: meta_tags/view_helper*displayingdescription*_spec.rb.
RSpec/FilePath:
  Enabled: false

# The second argument to describe should be the method being tested. '#instance' or '.class'. (http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/DescribeMethod)
# example: describe MetaTags::ViewHelper, 'displaying description' do
RSpec/DescribeMethod:
  Enabled: false

# Example has too many lines. (http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ExampleLength)
RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/NoExpectationExample:
  AllowedPatterns:
    - test_hashes_and_arrays

#-------------------------------------------------------------------------------
# Disabled rules
#-------------------------------------------------------------------------------

# Do not require loading Rails enviroment for Rake tasks as we are not a Rails application.
Rails/RakeEnvironment:
  Enabled: false

# Do not require subclassing from ApplicationController as we're not a rails application
Rails/ApplicationController:
  Enabled: false
