name: StandardRB

on:
  pull_request:
    types: [labeled]
permissions:
  contents: write

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'bundler')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby-version:
          - "3.2"

    name: Appraisal - Ruby ${{ matrix.ruby-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Update Appraisal gemfiles
        run: |
          bundle exec appraisal update
      - name: Commit gemfiles
        run: |
          git config --global user.name "Github Workflow"
          git config --global user.email "kpumuk@users.noreply.github.com"
          git add gemfiles/*
          git commit -am "Updated Appraisal gemfiles"
          git push
