name: StandardRB

on: [push, pull_request]
env:
  BUNDLE_GEMFILE: gemfiles/rails_7.0.gemfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-rubocop-${{ hashFiles('gemfiles/rails_7.0.gemfile') }}
          restore-keys: |
            ${{ runner.os }}-rubocop-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run StandardRB
        run: bundle exec standardrb --parallel
