name: Tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        rails-version:
          - "6.0"
          - "6.1"
          - "7.0"
          - "7.1"
          - "7.2"
        include:
          - ruby-version: "2.7"
            rails-version: ["5.1", "5.2"]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails-version }}.gemfile

    name: Specs - Ruby ${{ matrix.ruby-version }} on Rails ${{ matrix.rails-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run StandardRB
        run: |
          bundle exec rspec

