name: Tests

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "ruby-head"
        gemfile:
          - rails_5.1
          - rails_5.2
          - rails_6.0
          - rails_6.1
          - rails_7.0
          - rails_7.1
          - rails_7.2
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    name: Specs - Ruby ${{ matrix.ruby-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run StandardRB
        run: |
          bundle exec rspec

